name: Build Application

on:
  workflow_call:
    inputs:
      RUNS_ON:
        description: 'The type of machine to run on. Defaults to ubuntu-24.04.'
        required: true
        type: string
        default: ubuntu-24.04
      IMAGE_NAME:
        description: 'The name of the Docker image to build.'
        required: true
        type: string
      IMAGE_TAG:
        description: 'The tag to use for the Docker image.'
        required: true
        type: string
      PUSH:
        description: 'Whether to push the Docker image to the registry.'
        required: true
        type: boolean
      BUILD_CONTEXT:
        description: 'The context path for the Docker build. Defaults to the root of the repository.'
        required: false
        type: string
        default: '.'

jobs:
  build:
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Store.Client.Web/Dockerfile
          push: ${{ inputs.PUSH }}
          tags: |
            store-client-web:${{ inputs.IMAGE_TAG }}