name: CI - Application Web

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  id-token: write

jobs:
  generate-version:
    uses: ./.github/workflows/versioning.yaml
    with:
      RUNS_ON: ubuntu-24.04
      NODE_VERSION: '22'

  build-image:
    needs: generate-version
    uses: ./.github/workflows/build-docker.yaml
    with:
      RUNS_ON: ubuntu-24.04
      IMAGE_NAME: store/web
      IMAGE_TAG: ${{ needs.generate-version.outputs.VERSION }}
      PUSH: true
      BUILD_CONTEXT_PATH: .
      DOCKERFILE_PATH: src/Store.Client.Web/Dockerfile
      AWS_ROLE_ARN: arn:aws:iam::120915929317:role/repository-store
      AWS_ACCOUNT_ID: 120915929317
      AWS_REGION: eu-north-1

  fire-event:
    needs: build-image
    runs-on: ubuntu-24.04
    steps:
      - name: Generate deployment event
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: TheSteelMinistry/gitops-demo
          token: ${{ secrets.DEPLOYMENT_KEY }}
          event-type: new-image
          client-payload: '{
              "workload": "store",
              "image": "${{ needs.build-image.outputs.IMAGE_URI }}"
            }'